/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AppPackage;

import java.beans.Statement;
import java.sql.Connection;
import java.sql.ResultSet;

/**
 *
 * @author Zisis
 */
public class Menue extends javax.swing.JFrame {

    /**
     * Creates new form Menue
     */
    public Menue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        town = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        temp = new javax.swing.JLabel();
        celsius = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        dt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        windSpeed = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rain = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        snow = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        town.setBackground(new java.awt.Color(0, 0, 0));
        town.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        town.setForeground(new java.awt.Color(255, 255, 51));
        town.setText("Town");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, town, org.jdesktop.beansbinding.ELProperty.create("${}"), town, org.jdesktop.beansbinding.BeanProperty.create("displayedMnemonic"));
        bindingGroup.addBinding(binding);

        jPanel1.add(town, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 90, 30));

        country.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        country.setForeground(new java.awt.Color(255, 255, 51));
        country.setText("Counry");
        jPanel1.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        icon.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        icon.setForeground(new java.awt.Color(255, 255, 51));
        icon.setText("Icon");
        jPanel1.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 60, 50));

        temp.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        temp.setForeground(new java.awt.Color(255, 255, 51));
        temp.setText("Tempcurrent");
        jPanel1.add(temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 120, 150));

        celsius.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        celsius.setForeground(new java.awt.Color(255, 255, 51));
        celsius.setText("Celsius");
        jPanel1.add(celsius, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 70, 50));

        description.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        description.setForeground(new java.awt.Color(255, 255, 51));
        description.setText("description");
        jPanel1.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 220, 40));

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 51));
        id.setText("Id");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 40, 20));

        dt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dt.setForeground(new java.awt.Color(255, 255, 51));
        dt.setText("DateUTC");
        jPanel1.add(dt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 280, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Ένταση Ανέμου");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 150, -1));

        windSpeed.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        windSpeed.setForeground(new java.awt.Color(255, 255, 51));
        windSpeed.setText("WindSpeed");
        jPanel1.add(windSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Χιλιοστά Βροχής");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        rain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rain.setForeground(new java.awt.Color(255, 255, 51));
        rain.setText("Rain");
        jPanel1.add(rain, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Χιλιοστά χιονιού");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, -1, -1));

        snow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        snow.setForeground(new java.awt.Color(255, 255, 51));
        snow.setText("Snow");
        jPanel1.add(snow, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 320, -1, -1));

        wallpaper.setForeground(new java.awt.Color(255, 255, 255));
        wallpaper.setIcon(new javax.swing.ImageIcon("C:\\Users\\Zisis\\Documents\\NetBeansProjects\\eWeather\\src\\Wallpapers Weather\\wallpaper.wiki-Weather-Desktop-Pictures-PIC-WPE00205.jpg")); // NOI18N
        wallpaper.setText("jLabel1");
        wallpaper.setMaximumSize(new java.awt.Dimension(1280, 768));
        wallpaper.setMinimumSize(new java.awt.Dimension(1280, 768));
        wallpaper.setPreferredSize(new java.awt.Dimension(1280, 768));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, wallpaper, org.jdesktop.beansbinding.ELProperty.create("${}"), wallpaper, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        jPanel1.add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 770));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
          
               

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel celsius;
    private javax.swing.JLabel country;
    private javax.swing.JLabel description;
    private javax.swing.JLabel dt;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rain;
    private javax.swing.JLabel snow;
    private javax.swing.JLabel temp;
    private javax.swing.JLabel town;
    private javax.swing.JLabel wallpaper;
    private javax.swing.JLabel windSpeed;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
